# Generated by Django 5.0.14 on 2026-07-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoInstitutionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('legal_sk_number', models.CharField(max_length=100)),
                ('npwp', models.CharField(max_length=20)),
                ('pub_permit_no', models.CharField(max_length=100)),
                ('bank_account_no', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_account_name', models.CharField(max_length=150)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('is_frozen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'institutions',
            },
        ),
    ]
